name: base_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  auto_route: ^7.7.0
  dartz: ^0.10.1
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  intl: any
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.0
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.2.0
  build_runner: ^2.4.6
  freezed: ^2.3.5
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true

  # Local assets
  assets:
    - assets/images/
    - assets/icons/  
